### ISSUE TITLE
Draw map does not save anything and swapping kml is not working

### ISSUE THREAD

**Issue by Hanzolo** [nlybe/Elgg-Sharemaps#10]
First of all: Thank you for this plugin!
I am using elgg 2.1.1 on an Apache/2.2.15 (CentOS) Server with php 5.6.9
Most of the features seem to work nicely. But when I try to draw a map (e.g. place a marker) and save it, nothing is saved at all. The map jumps back and shows Montecarlo... I have no clue why!
And when I try to swap the kml file of a saved map, I get a server error. 
Could be because of elgg 2.1.1 ???

**Comment by nlybe** [comment]
This plugin hasn't been tested on Elgg 2.x yet and probably will not work since there are big changes on hos the js functions are loaded

**Comment by Hanzolo** [comment]
Thank you! That is what I thought. Are there any plans to upgrade that awesome plugin to 2.x?

**Comment by nlybe** [comment]
Yes, sure it's on my plan. The only problem is to find time to make the upgrade :)
