### ISSUE TITLE
Can't make it work in Elgg 2.3.3

### ISSUE THREAD

**Issue by lcardoso1970** [nlybe/Elgg-Sharemaps#12]
not saving the places neither exhibiting the map after 1st submission

**Comment by AndreyAtGitHub** [comment]
> not saving the places neither exhibiting the map after 1st submission

I've asked the developer at the Elgg Community Discussion - there is the answer

> for Elgg 2.x you should use only the 2.11.1, which works fine if want to upload maps (kml or gpx file). But the functionality for creating maps online is not completed yet, that's why you probably get these errors. But you can disable this on settings if the rest functionality cover you.

[https://elgg.org/discussion/view/2767481/latest-beta-version-19-sharemaps-plugin-does-not-work-correctly-elgg-236](url)
