### ISSUE TITLE
Upgrade to 5.0

### ISSUE THREAD

**Issue by oranyero** [nlybe/Elgg-Sharemaps#13]
Could upgrade to version 5.0?
Thank you.

**Comment by nlybe** [comment]
It's on my plan to upgrade the plugin but at the moment is low priority due to other plugins upgrades for clients.
Hopefully it will be upgraded before the end of the year

**Comment by oranyero** [comment]
If it would be good, since it is a good complement.
Thank you.

**Comment by nlybe** [comment]
@oranyero at https://github.com/nlybe/Elgg-Sharemaps/tree/5.x you can download an Elgg 5.x compatible version of sharemaps.
It's not really full tested but normally it works fine
