### ISSUE TITLE
Comments and Likes don´t work with sharemaps

### ISSUE THREAD

**Issue by schmidtwastl** [nlybe/Elgg-Sharemaps#5]
For me, Comments and Likes don´t work with sharemaps!

At all other plugins(blogs, Events, your classifieds-plugin) the comments and likes load fine via ajax. Only at sharemaps, the browser tries to load a complete new page: "example.com/stream/comments/16478" with no content (just white)

At first I thought it is an issue with hypeInteractions or hypeLists..But as the comments are loaded corretly for all other plugins, I wonder why it does not work for me with sharemaps?

The strange thing is that it works in 1 out of 10 cases to load the comments..

I am using elgg 1.9.8

**Comment by nlybe** [comment]
fixed
