### ISSUE TITLE
A small bug in the plugin share_maps

### ISSUE THREAD

**Issue by olairmarcos** [nlybe/Elgg-Sharemaps#8]
A small bug in the plugin share maps
When creating a new Marker saved with a name. When we edit the map to add a Marker new, it is not saved the old Marker with his name previously saved. It is saved with the name Marker # 0. Whenever we edit the map to add a Marker new the old name is renamed to the name default.

Thanks

**Comment by nlybe** [comment]
This issue fixed in 1.12.9 version
