### ISSUE TITLE
You can not activate the plugin Sharemaps in Elgg

### ISSUE THREAD

**Issue by olairmarcos** [nlybe/Elgg-Sharemaps#9]
You can not activate the plugin Sharemaps in Elgg 1.12.8. see the image.
Thank you for your help.
![2016-02-08_105414](https://cloud.githubusercontent.com/assets/8938718/12886254/19599ad0-ce53-11e5-8d84-9bda080a4a9b.jpg)

**Comment by nlybe** [comment]
fixed
